Repository bcgov/MoH-SAT, pull requests merged in 2024-11, with the labels that each got.

#1351 BCMOHAM-19780 - Changes related to Pick list Value addition
  force-app/main/default/classes/ODRIntegration.cls
  force-app/main/default/classes/ODRIntegrationTest.cls
  force-app/main/default/objects/Contact/fields/Provider_Type__c.field-meta.xml
  force-app/main/default/objects/PersonAccount/recordTypes/Provider.recordType-meta.xml
Labels: enhancement

#1386 BCMOHAD-26462 || Updated the field permission
  force-app/main/default/layouts/Case-SA Request.layout-meta.xml
Labels: bug

#1394 BCMOHAM-21220 || Updated the flow with new error messages
  dev-app-post/main/default/flows/Create_EDRD_Case.flow-meta.xml
Labels: bug, on hold
