Repository bcgov/MoH-SAT, pull requests merged in 2025-03, with the labels that each got.

#1516 BCMOHAD-28087 || Updated the frequency from often to Always
  force-app/main/default/animationRules/EC_Path.animationRule-meta.xml
Labels: enhancement

#1527 BCMOHAD-28145 || Created new Batch and Scheduler classes
  force-app/main/default/classes/ContentVersionBatch.cls
  force-app/main/default/classes/ContentVersionBatch.cls-meta.xml
  force-app/main/default/classes/ContentVersionBatchScheduler.cls
  force-app/main/default/classes/ContentVersionBatchScheduler.cls-meta.xml
  force-app/main/default/classes/ContentVersionBatchSchedulerTest.cls
  force-app/main/default/classes/ContentVersionBatchSchedulerTest.cls-meta.xml
  force-app/main/default/classes/ContentVersionBatchTest.cls
  force-app/main/default/classes/ContentVersionBatchTest.cls-meta.xml
Labels: bug, enhancement

#1498 BCMOHAD-27107 || Updated the API Version to 61.0
  dev-app-post/main/default/classes/AccountContactRelationTriggerHandlerTest.cls-meta.xml
  dev-app-post/main/default/classes/EDRDAccountContactShare_Test.cls-meta.xml
  dev-app-post/main/default/classes/EDRDShareMedicationReqwithAccCon_Test.cls-meta.xml
  dev-app-post/main/default/classes/EDRD_myPatientsControllerTest.cls-meta.xml
  dev-app-post/main/default/classes/UserTriggerHandlerTest.cls-meta.xml
  dev-app-post/main/default/flows/Create_EDRD_Case.flow-meta.xml
  dev-app-post/main/default/flows/EDRD_Change_Enrollee_Status_OnPatient.flow-meta.xml
  dev-app-post/main/default/lwc/eDRD_lwc_customSaveforlater/eDRD_lwc_customSaveforlater.js-meta.xml
  force-app/main/default/classes/AccountContactRelationTriggerHandler.cls-meta.xml
  force-app/main/default/classes/AccountContactShareHelper.cls-meta.xml
  force-app/main/default/classes/AccountSelector.cls-meta.xml
  force-app/main/default/classes/AccountTriggerHelper.cls-meta.xml
  force-app/main/default/classes/EDRDAccountContactShare.cls-meta.xml
  force-app/main/default/classes/EDRDAccountLookupController.cls-meta.xml
  force-app/main/default/classes/EDRDAccountLookupController_Test.cls-meta.xml
  force-app/main/default/classes/EDRDMedicationReqwithACRHandler.cls-meta.xml
  force-app/main/default/classes/EDRD_cls_DrugCostCalculator.cls-meta.xml
  force-app/main/default/classes/EDRD_cls_DrugCostCalculatorTest.cls-meta.xml
  force-app/main/default/classes/EDRD_cls_FundingForecastController.cls-meta.xml
  force-app/main/default/classes/EDRD_cls_FundingForecastControllerTest.cls-meta.xml
  force-app/main/default/classes/EDRD_cls_IndefiniteBatchTest.cls-meta.xml
  force-app/main/default/classes/EDRD_cls_ShowToastMsgController.cls-meta.xml
  force-app/main/default/classes/EDRD_cls_ShowToastMsgControllerTest.cls-meta.xml
  force-app/main/default/classes/EDRD_cls_omniSObjectQuery.cls-meta.xml
  force-app/main/default/classes/EDRD_cls_omniSObjectQueryCallable.cls-meta.xml
  force-app/main/default/classes/EDRD_cls_omniSObjectQueryCallable_Test.cls-meta.xml
  force-app/main/default/classes/EDRD_myPatientsController.cls-meta.xml
  force-app/main/default/classes/MedicationTriggerHandler.cls-meta.xml
  force-app/main/default/classes/UserTriggerHandler.cls-meta.xml
  force-app/main/default/classes/UserTriggerHelper.cls-meta.xml
  force-app/main/default/classes/medicationRequestTriggerHandler.cls-meta.xml
  force-app/main/default/classes/medicationRequestTriggerHandlerTest.cls-meta.xml
  force-app/main/default/classes/medicinalIngredientTriggerHandler.cls-meta.xml
  force-app/main/default/classes/medicinalIngredientTriggerHandlerTest.cls-meta.xml
  force-app/main/default/flows/Account_Contact_Case_Share.flow-meta.xml
  force-app/main/default/flows/EDRD_Medication_Request_Flow.flow-meta.xml
  force-app/main/default/lwc/eDRD_LC_ShowToastMessageOnCase/eDRD_LC_ShowToastMessageOnCase.js-meta.xml
  force-app/main/default/lwc/edrdMyPatients/edrdMyPatients.js-meta.xml
  force-app/main/default/lwc/providerAccountComp/providerAccountComp.js-meta.xml
  force-app/main/default/triggers/AccountContactRelationTrigger.trigger-meta.xml
  force-app/main/default/triggers/CarePgmEnrolleeTrigger.trigger-meta.xml
  force-app/main/default/triggers/MedicationRequestTrigger.trigger-meta.xml
  force-app/main/default/triggers/MedicationTrigger.trigger-meta.xml
  force-app/main/default/triggers/MedicinalIngredientTrigger.trigger-meta.xml
  force-app/main/default/triggers/UserTrigger.trigger-meta.xml
  manifest/profiles.xml
Labels: enhancement

#1536 BCMOHAD-28193 || Updated the class with Trim and Truncate
  force-app/main/default/classes/ContentVersionBatch.cls
Labels: bug, enhancement

#1545 BCMOHAM-23301 || Updated the NP value int picklist value
  force-app/main/default/objects/Drug_Template__c/fields/Excluded_Plans__c.field-meta.xml
  force-app/main/default/objects/Step_Action__c/fields/Excluded_Plans__c.field-meta.xml
  force-app/main/default/objects/Step_Action__c/recordTypes/ESA_RT_Case_Update.recordType-meta.xml
  force-app/main/default/objects/Step_Action__c/recordTypes/Pharmanet_Payload.recordType-meta.xml
Labels: enhancement

#1544 BCMOHAD-28178
  force-app/main/default/lwc/patientLookup/patientLookup.html
  force-app/main/default/lwc/patientLookup/patientLookup.js
Labels: bug
